language: python
python:
- '3.3'
- '3.4'
- nightly
matrix:
  allow_failures:
    - python: nightly
cache:
  directory:
    - "$HOME/.cache/pip"
install:
- pip install -r test_requirements.txt
- pip install .
script:
- nosetests
